server {
    listen 80;
    server_name eliasrodriguezdev.com.ar;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 80;
    server_name op.eliasrodriguezdev.com.ar;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name eliasrodriguezdev.com.ar;

    ssl_certificate /etc/letsencrypt/live/eliasrodriguezdev.com.ar/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/eliasrodriguezdev.com.ar/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    root /var/www/portfolio-elias;
    index index.html;
}

server {
    listen 443 ssl;
    server_name op.eliasrodriguezdev.com.ar;

    ssl_certificate /etc/letsencrypt/live/eliasrodriguezdev.com.ar/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/eliasrodriguezdev.com.ar/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    root /var/www/ofipro-fronted/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}