server {
    listen 80;
    server_name eliasrodriguezdev.com.ar;
    root /var/www/portfolio-elias;
    index index.html;
}

server {
    listen 80;
    server_name op.eliasrodriguezdev.com.ar;
    root /var/www/ofipro-fronted/dist; 



    index index.html;
location / {
        try_files $uri $uri/ /index.html;
    }

}



#server {
#    listen 81;
#    server_name localhost;
#    root /var/www/sitio2;
#    index index.html;
#}

