# 80 eliasrodriguezdev.com.ar
server {
    listen 80;
    server_name eliasrodriguezdev.com.ar;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# 80 op.eliasrodriguezdev.com.ar
server {
    listen 80;
    server_name op.eliasrodriguezdev.com.ar;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# 80 gestoreconomico.eliasrodriguezdev.com.ar
server {
    listen 80;
    server_name gestoreconomico.eliasrodriguezdev.com.ar;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# 443 eliasrodriguezdev.com.ar
server {
    listen 443 ssl;
    server_name eliasrodriguezdev.com.ar;

    ssl_certificate /etc/letsencrypt/live/eliasrodriguezdev.com.ar/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/eliasrodriguezdev.com.ar/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    root /var/www/portfolio-elias;
    index index.html;
}

# 443 op.eliasrodriguezdev.com.ar
server {
    listen 443 ssl;
    server_name op.eliasrodriguezdev.com.ar;

    ssl_certificate /etc/letsencrypt/live/eliasrodriguezdev.com.ar/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/eliasrodriguezdev.com.ar/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    location /api/ {
        proxy_pass http://theop-api:3004/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    root /var/www/ofipro-fronted/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

# 443 gestoreconomico.eliasrodriguezdev.com.ar
server {
    listen 443 ssl;
    server_name gestoreconomico.eliasrodriguezdev.com.ar;

    ssl_certificate /etc/letsencrypt/live/eliasrodriguezdev.com.ar/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/eliasrodriguezdev.com.ar/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    location /api/ {
    proxy_pass http://backend-spring:3002/api/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}

    root /var/www/gestor-economico-frontend/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}